# Generated by Django 3.0.5 on 2020-04-13 02:52

from django.db import migrations, models
import upDown.common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.FileField(null=True, upload_to=upDown.common.file_upload_path)),
            ],
        ),
    ]
